import Head from "next/head";
import styles from "./Home.module.scss";
import { motion } from "framer-motion";
import { variants } from "./index.motion.js";

import { Canvas } from "@react-three/fiber";
import Link from "next/link";

import { Box } from "@components/Box.js";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.flex}>
        <Canvas className={styles.flexLeft} dpr={[2, 3]}>
          <ambientLight />
          <pointLight position={[10, 10, 10]} />
          <Box position={[-1.2, 0, 0]} />
          <Box position={[1.2, 0, 0]} />
        </Canvas>
        <div className={styles.flexRight}>
          <motion.div initial={"initial"} animate={"animate"} exit={"exit"}>
            <motion.h1 variants={variants.title}>Home</motion.h1>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
